version: '3'

services:
  web1:
    build:
      .
    container_name: php1
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql1
    links:
      - mysql1

  mysql1:
    image: mysql:5.7.27
    container_name: mysql-server1
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: blog